# Generated by Django 4.2.6 on 2023-11-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles', models.CharField(help_text='ФИО', max_length=35)),
                ('mails', models.CharField(help_text='почта', max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название картины', max_length=35)),
                ('pictures', models.ImageField(help_text='фото картины', upload_to='')),
                ('genres', models.IntegerField(default=0, help_text='1 - портреты, 2 - живопись, 3 - абстракция,  4 - графика, 5 - светящиеся')),
                ('instock', models.IntegerField(default=0, help_text='0 - в коллекции, 1 - в наличии')),
                ('description', models.TextField(help_text='описание картины')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.TextField(help_text='cсылка на видео ютуб')),
                ('body', models.TextField(help_text='описание видео')),
                ('header', models.TextField(help_text='заголовок видео')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='фото новости', upload_to='')),
                ('body', models.TextField(help_text='текст новости')),
                ('header', models.CharField(help_text='заголовок новости', max_length=35)),
                ('date', models.DateField(auto_now_add=True, help_text='дата новости')),
            ],
        ),
    ]
