# Generated by Django 4.2.4 on 2024-01-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobrinapp', '0002_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'картину', 'verbose_name_plural': 'Картины'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
