# Generated by Django 4.2.6 on 2024-02-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobrinapp', '0003_alter_clients_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(help_text='ФИО', max_length=35)),
                ('emails', models.CharField(help_text='почта', max_length=35)),
                ('phone', models.CharField(help_text='Телефон', max_length=35)),
                ('comment', models.TextField(help_text='Комментарий', max_length=235)),
            ],
            options={
                'verbose_name': 'заказа',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
